version: '3.8'

services:
  premiereshield-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: premiereshield-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
